apiVersion: v1
kind: Service
metadata: 
    name: mywebserversvc
spec:
    type: NodePort
    ports:
        - port: 80
        protocol: TCP #optional
    selector:
        app: httpd #must match with Deployment metadata labels